words = [
    "Addop",
    "CLR",
    "Crenshaw's",
    "EOF",
    "EXG",
    "MULS",
    "Mulop",
    "alnum",
    "cli",
    "ctos",
    "emitln",
    "getchar",
    "mul",
    "prg",
    "scat",
    "strs",
    "unaryop",
]
